
export const counties = [
    { value: "Alba", label: "Alba" },
    { value: "Arad", label: "Arad" },
    { value: "Argeș", label: "Argeș" },
    { value: "Bacău", label: "Bacău" },
    { value: "Bihor", label: "Bihor" },
    { value: "Bistrița-Năsăud", label: "Bistrița-Năsăud" },
    { value: "Botoșani", label: "Botoșani" },
    { value: "Brașov", label: "Brașov" },
    { value: "Brăila", label: "Brăila" },
    { value: "Buzău", label: "Buzău" },
    { value: "București", label: "București" },
    { value: "Caraș-Severin", label: "Caraș-Severin" },
    { value: "Călărași", label: "Călărași" },
    { value: "Cluj", label: "Cluj" },
    { value: "Constanța", label: "Constanța" },
    { value: "Covasna", label: "Covasna" },
    { value: "Dâmbovița", label: "Dâmbovița" },
    { value: "Dolj", label: "Dolj" },
    { value: "Galați", label: "Galați" },
    { value: "Giurgiu", label: "Giurgiu" },
    { value: "Gorj", label: "Gorj" },
    { value: "Harghita", label: "Harghita" },
    { value: "Hunedoara", label: "Hunedoara" },
    { value: "Ialomița", label: "Ialomița" },
    { value: "Iași", label: "Iași" },
    { value: "Ilfov", label: "Ilfov" },
    { value: "Maramureș", label: "Maramureș" },
    { value: "Mehedinți", label: "Mehedinți" },
    { value: "Mureș", label: "Mureș" },
    { value: "Neamț", label: "Neamț" },
    { value: "Olt", label: "Olt" },
    { value: "Prahova", label: "Prahova" },
    { value: "Sate Mare", label: "Satu Mare" },
    { value: "Sălaj", label: "Sălaj" },
    { value: "Sibiu", label: "Sibiu" },
    { value: "Suceava", label: "Suceava" },
    { value: "Teleorman", label: "Teleorman" },
    { value: "Timiș", label: "Timiș" },
    { value: "Tulcea", label: "Tulcea" },
    { value: "Vaslui", label: "Vaslui" },
    { value: "Vâlcea", label: "Vâlcea" },
    { value: "Vrancea", label: "Vrancea" },
  ];
