export const medicalSpecialties = [
    {
      value: "Alergologie și imunologie clinică",
      label: "Allergology and Clinical Immunology",
    },
    { value: "Anatomie patologică", label: "Pathological Anatomy" },
    {
      value: "Anestezie și terapie intensivă",
      label: "Anesthesia and Intensive Care",
    },
    { value: "Boli infecțioase", label: "Infectious Diseases" },
    { value: "Cardiologie", label: "Cardiology" },
    { value: "Chirurgie cardiovasculară", label: "Cardiovascular Surgery" },
    { value: "Chirurgie generală", label: "General Surgery" },
    { value: "Chirurgie maxilo-facială", label: "Maxillofacial Surgery" },
    { value: "Chirurgie pediatrică", label: "Pediatric Surgery" },
    {
      value: "Chirurgie plastică, estetică și reconstructivă",
      label: "Plastic, Aesthetic and Reconstructive Surgery",
    },
    { value: "Chirurgie toracică", label: "Thoracic Surgery" },
    { value: "Chirurgie vasculară", label: "Vascular Surgery" },
    {
      value: "Dermatovenerologie",
      label: "Dermatology and Venereology",
    },
    {
      value: "Diabet, nutriție și boli metabolice",
      label: "Diabetes, Nutrition and Metabolic Diseases",
    },
    { value: "Endocrinologie", label: "Endocrinology" },
    { value: "Epidemiologie", label: "Epidemiology" },
    { value: "Farmacologie clinică", label: "Clinical Pharmacology" },
    {
      value: "Gastroenterologie",
      label: "Gastroenterology",
    },
    {
      value: "Gastroenterologie și hepatologie",
      label: "Gastroenterology and Hepatology",
    },
    { value: "Genetică medicală", label: "Medical Genetics" },
    { value: "Geriatrie și gerontologie", label: "Geriatrics and Gerontology" },
    { value: "Hematologie", label: "Hematology" },
    { value: "Igienă", label: "Hygiene" },
    {
      value: "Infecțioase și medicină tropicală",
      label: "Infectious and Tropical Medicine",
    },
    { value: "Medicină de familie", label: "Family Medicine" },
    { value: "Medicină de laborator", label: "Laboratory Medicine" },
    { value: "Medicină de urgență", label: "Emergency Medicine" },
    {
      value: "Medicină fizică și de reabilitare",
      label: "Physical Medicine and Rehabilitation",
    },
    { value: "Medicină generală", label: "General Medicine" },
    { value: "Medicină internă", label: "Internal Medicine" },
    { value: "Medicină legală", label: "Forensic Medicine" },
    { value: "Medicină nucleară", label: "Nuclear Medicine" },
    { value: "Medicină ocupatională", label: "Occupational Medicine" },
    { value: "Medicină sportivă", label: "Sports Medicine" },
    { value: "Neonatologie", label: "Neonatology" },
    { value: "Nefrologie", label: "Nefrology" },
    { value: "Neurochirurgie", label: "Neurosurgery" },
    { value: "Neurologie", label: "Neurology" },
    { value: "Obstetrică-ginecologie", label: "Obstetrics and Gynecology" },
    { value: "Oftalmologie", label: "Ophthalmology" },
    { value: "Oncologie medicală", label: "Medical Oncology" },
    {
      value: "Oncologie și hematologie pediatrică",
      label: "Oncology and Pediatric Hematology",
    },

    {
      value: "Ortopedie și traumatologie",
      label: "Orthopedics and Traumatology",
    },
    { value: "Otorinolaringologie", label: "Otorhinolaryngology" },
    { value: "Pediatrie", label: "Pediatrics" },
    { value: "Pneumologie", label: "Pulmonology" },
    { value: "Psihiatrie", label: "Psychiatry" },
    { value: "Psihiatrie pediatrică", label: "Child Psychiatry" },
    {
      value: "Radiologie - imagistică medicală",
      label: "Radiology and Medical Imaging",
    },
    { value: "Recuperare medicală", label: "Medical Recovery" },
    { value: "Reumatologie", label: "Rheumatology" },
    { value: "Sănătate publică", label: "Public Health" },
    { value: "Transfuzii sanguine", label: "Blood Transfusions" },
    { value: "Urolog", label: "Urology" },
  ];